// Media
export const SET_AUTH_INFO = "SET_AUTH_INFO";
export const SET_LOGIN_FAILED = "SET_LOGIN_FAILED";
export const SET_ALL_MEDIA = "SET_ALL_MEDIA";
export const SET_COUNT = "SET_COUNT";
export const SET_MEDIA_LOADING = "SET_MEDIA_LOADING";
export const SET_CURRENT_NOTIFICATION = "SET_CURRENT_NOTIFICATION";
export const SET_LOADING_NOTIFICATION = "SET_LOADING_NOTIFICATION";
export const SET_MEDIA_BADGE = "SET_MEDIA_BADGE";
export const SET_ADDRESSES = "SET_ADDRESSES";
export const LOG_OUT = "LOG_OUT";
export const SET_CLEARANCE_BADGE = "SET_CLEARANCE_BADGE";
export const SET_ALL_CLEARANCE = "SET_ALL_CLEARANCE";
export const SET_PENDING_CLEARANCE = "SET_PENDING_CLEARANCE";
export const SET_ISSUED_CLEARANCE = "SET_ISSUED_CLEARANCE";
export const SET_VERIFIED_CLEARANCE = "SET_VERIFIED_CLEARANCE";
export const SET_CASE_BADGE = "SET_CASE_BADGE";
export const SET_ALL_CASE = "SET_ALL_CASE";
export const SET_USERS = "SET_USERS";
export const SET_RELATED_CASE = "SET_RELATED_CASE";
export const ADD_CASE = "ADD_CASE";
export const UPDATE_CASE = "UPDATE_CASE";
export const UPDATE_PERSONNEL = "UPDATE_PERSONNEL";
export const SET_CURRENT_CLEARANCE = "SET_CURRENT_CLEARANCE";
export const SET_CURRENT_CLEARANCE_TO_RENEW = "SET_CURRENT_CLEARANCE_TO_RENEW";
export const SET_ADDED_CLEARANCE = "SET_ADDED_CLEARANCE";
export const SET_ISSUED_CLEARANCE_COUNT = "SET_ISSUED_CLEARANCE_COUNT";
export const SET_ADDED_APPLICANT = "SET_ADDED_APPLICANT";
export const SET_ALL_APPLICANT = "SET_ALL_APPLICANT";

export const SET_ALL_POLICE = "SET_ALL_POLICE";

export const SET_HAS_RELATED_DIALOG = "SET_HAS_RELATED_DIALOG";

export const SET_APPROVED_CLEARANCE = "SET_APPROVED_CLEARANCE";
export const ADD_POLICE = "ADD_POLICE";

// Statistic
export const SET_CLEARANCE_ISSUED_STATISTICS =
  "SET_CLEARANCE_ISSUED_STATISTICS";

export const SET_CLEARANCE_INCOME_STATISTICS =
  "SET_CLEARANCE_INCOME_STATISTICS";
